### ISSUE TITLE
Repo name?

### ISSUE THREAD

**Issue by eitsupi** [rpolars/r-polarssql#1]
@sorhawell @etiennebacher I have started to create a DBI backend using the `polars` package as described in pola-rs/r-polars#457.

For now, I use repository name `r-polarssql` and package name `polarssql`. Can I put it here?

**Comment by etiennebacher** [comment]
I don't have anything against it, I just don't think there's added value compared to hosting it on your account. Or do you plan on making multiple `polars`-related packages?

Sidenote: I find `polars.sql` easier to read as a package name, just my 2 cents ;)

**Comment by eitsupi** [comment]
> I don't have anything against it, I just don't think there's added value compared to hosting it on your account.

This is because installation across multiple R-universe is cumbersome.
(Of course I could solve this by putting `polars` on my R-universe, but it seemed better to put this package here)

> Sidenote: I find `polars.sql` easier to read as a package name, just my 2 cents ;)

I did not want to use a dot in the package name. (like <https://cran.r-project.org/package=adbcdrivermanager>)

**Comment by eitsupi** [comment]
Thanks for your replies.
I would like to leave it like this for a while.
